# Generated by Django 5.0.1 on 2024-08-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('acquisition_date', models.DateField()),
                ('custodian', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('useful_life', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scrap_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('classification', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location')),
            ],
        ),
    ]
